"""Source maps for KOF central bank governors processing."""

SOURCE_URLS = {
    "AFG": "https://dab.gov.af",
    "ALB": "https://www.bankofalbania.org",
    "DZA": "https://www.bank-of-algeria.dz",
    "AGO": "https://www.bna.ao",
    "ARG": "https://www.bcra.gob.ar",
    "ARM": "https://www.cba.am",
    "ABW": "https://www.cba.aw",
    "AUS": "https://www.rba.gov.au",
    "AUT": "https://www.oenb.at",
    "AZE": "https://www.cbar.az",
    "BHS": "https://www.centralbankbahamas.com",
    "BHR": "https://www.cbb.gov.bh",
    "BGD": "https://www.bb.org.bd",
    "BRB": "https://www.centralbank.org.bb",
    "BLR": "https://www.nbrb.by",
    "BEL": "https://www.nbb.be",
    "BLZ": "https://www.centralbank.org.bz",
    "BEN": "https://www.bceao.int",
    "BMU": "https://www.bma.bm",
    "BTN": "https://www.rma.org.bt",
    "BOL": "https://www.bcb.gob.bo",
    "BIH": "https://www.cbbh.ba",
    "BWA": "https://www.bankofbotswana.bw",
    "BRA": "https://www.bcb.gov.br",
    "BRN": "https://www.ambd.gov.bn",
    "BGR": "https://www.bnb.bg",
    "BFA": "https://www.bceao.int",
    "BDI": "https://www.brb.bi",
    "KHM": "https://www.nbc.gov.kh",
    "CMR": "https://www.beac.int",
    "CAN": "https://www.bankofcanada.ca",
    "CAF": "https://www.beac.int",
    "TCD": "https://www.beac.int",
    "CHL": "https://www.bcentral.cl",
    "CHN": "https://www.pbc.gov.cn",
    "COL": "https://www.banrep.gov.co",
    "COM": "https://www.bcc.km",
    "COG": "https://www.beac.int",
    "COD": "https://www.bcc.cd",
    "CRI": "https://www.bccr.fi.cr",
    "HRV": "https://www.hnb.hr",
    "CUB": "https://www.bc.gob.cu",
    "CYP": "https://www.centralbank.cy",
    "CZE": "https://www.cnb.cz",
    "DNK": "https://www.nationalbanken.dk",
    "DJI": "https://www.banque-centrale.dj",
    "DOM": "https://www.bancentral.gov.do",
    "ECU": "https://www.bce.fin.ec",
    "EGY": "https://www.cbe.org.eg",
    "SLV": "https://www.bcr.gob.sv",
    "GNQ": "https://www.beac.int",
    "ERI": "https://www.bankoferitreanot.er",
    "EST": "https://www.eestipank.ee",
    "SWZ": "https://www.centralbank.org.sz",
    "ETH": "https://nbe.gov.et",
    "FJI": "https://www.rbf.gov.fj",
    "FIN": "https://www.suomenpankki.fi",
    "FRA": "https://www.banque-france.fr",
    "GAB": "https://www.beac.int",
    "GMB": "https://www.cbg.gm",
    "GEO": "https://www.nbg.gov.ge",
    "DEU": "https://www.bundesbank.de",
    "GHA": "https://www.bog.gov.gh",
    "GRC": "https://www.bankofgreece.gr",
    "GTM": "https://www.banguat.gob.gt",
    "GIN": "https://www.bcrg-guinee.org",
    "GNB": "https://www.bceao.int",
    "GUY": "https://www.bankofguyana.org.gy",
    "HTI": "https://www.brh.net",
    "HND": "https://www.bch.hn",
    "HKG": "https://www.hkma.gov.hk",
    "HUN": "https://www.mnb.hu",
    "ISL": "https://www.cb.is",
    "IND": "https://www.rbi.org.in",
    "IDN": "https://www.bi.go.id",
    "IRN": "https://www.cbi.ir",
    "IRQ": "https://www.cbi.iq",
    "IRL": "https://www.centralbank.ie",
    "ISR": "https://www.boi.org.il",
    "ITA": "https://www.bancaditalia.it",
    "JAM": "https://www.boj.org.jm",
    "JPN": "https://www.boj.or.jp",
    "JOR": "https://www.cbj.gov.jo",
    "KAZ": "https://www.nationalbank.kz",
    "KEN": "https://www.centralbank.go.ke",
    "PRK": "https://www.kcna.kp",
    "KOR": "https://www.bok.or.kr",
    "KWT": "https://www.cbk.gov.kw",
    "KGZ": "https://www.nbkr.kg",
    "LAO": "https://www.bol.gov.la",
    "LVA": "https://www.bank.lv",
    "LBN": "https://www.bdl.gov.lb",
    "LSO": "https://www.centralbank.org.ls",
    "LBR": "https://www.cbl.org.lr",
    "LBY": "https://cbl.gov.ly",
    "LTU": "https://www.lb.lt",
    "LUX": "https://www.bcl.lu",
    "MAC": "https://www.amcm.gov.mo",
    "MDG": "https://www.banky-foiben'ny-madagasikara.mg",
    "MWI": "https://www.rbm.mw",
    "MYS": "https://www.bnm.gov.my",
    "MDV": "https://www.mma.gov.mv",
    "MLI": "https://www.bceao.int",
    "MLT": "https://www.centralbankmalta.org",
    "MRT": "https://www.bcm.mr",
    "MUS": "https://www.bom.mu",
    "MEX": "https://www.banxico.org.mx",
    "MDA": "https://www.bnm.md",
    "MNG": "https://www.mongolbank.mn",
    "MNE": "https://www.cbcg.me",
    "MAR": "https://www.bkam.ma",
    "MOZ": "https://www.bancomoc.mz",
    "MMR": "https://www.cbm.gov.mm",
    "NAM": "https://www.bon.com.na",
    "NPL": "https://www.nrb.org.np",
    "NLD": "https://www.dnb.nl",
    "NZL": "https://www.rbnz.govt.nz",
    "NIC": "https://www.bcn.gob.ni",
    "NER": "https://www.bceao.int",
    "NGA": "https://www.cbn.gov.ng",
    "MKD": "https://www.nbrm.mk",
    "NOR": "https://www.norges-bank.no",
    "OMN": "https://www.cbo.gov.om",
    "PAK": "https://www.sbp.org.pk",
    "PSE": "https://www.pma.ps",
    "PAN": "https://www.superbancos.gob.pa",
    "PNG": "https://www.bankpng.gov.pg",
    "PRY": "https://www.bcp.gov.py",
    "PER": "https://www.bcrp.gob.pe",
    "PHL": "https://www.bsp.gov.ph",
    "POL": "https://www.nbp.pl",
    "PRT": "https://www.bportugal.pt",
    "QAT": "https://www.qcb.gov.qa",
    "ROU": "https://www.bnr.ro",
    "RUS": "https://www.cbr.ru",
    "RWA": "https://www.bnr.rw",
    "SAU": "https://www.sama.gov.sa",
    "SEN": "https://www.bceao.int",
    "SRB": "https://www.nbs.rs",
    "SYC": "https://www.cbs.sc",
    "SLE": "https://www.bsl.gov.sl",
    "SGP": "https://www.mas.gov.sg",
    "SVK": "https://www.nbs.sk",
    "SVN": "https://www.bsi.si",
    "SLB": "https://www.cbsi.com.sb",
    "SOM": "https://www.centralbank.gov.so",
    "ZAF": "https://www.resbank.co.za",
    "SSD": "https://www.bss.gov.ss",
    "ESP": "https://www.bde.es",
    "LKA": "https://www.cbsl.gov.lk",
    "SDN": "https://www.cbos.gov.sd",
    "SUR": "https://www.cbvs.sr",
    "SWE": "https://www.riksbank.se",
    "CHE": "https://www.snb.ch",
    "SYR": "https://www.cb.gov.sy",
    "TWN": "https://www.cbc.gov.tw",
    "TJK": "https://www.nbt.tj",
    "TZA": "https://www.bot.go.tz",
    "THA": "https://www.bot.or.th",
    "TLS": "https://www.bancocentral.tl",
    "TGO": "https://www.bceao.int",
    "TON": "https://www.nrbt.to",
    "TTO": "https://www.central-bank.org.tt",
    "TUN": "https://www.bct.gov.tn",
    "TUR": "https://www.tcmb.gov.tr",
    "TKM": "https://www.cbt.gov.tm",
    "UGA": "https://www.bou.or.ug",
    "UKR": "https://www.bank.gov.ua",
    "ARE": "https://www.centralbank.ae",
    "GBR": "https://www.bankofengland.co.uk",
    "USA": "https://www.federalreserve.gov",
    "URY": "https://www.bcu.gub.uy",
    "UZB": "https://www.cbu.uz",
    "VUT": "https://www.rbv.gov.vu",
    "VEN": "https://www.bcv.org.ve",
    "VNM": "https://www.sbv.gov.vn",
    "YEM": "https://www.centralbank.gov.ye",
    "ZMB": "https://www.boz.zm",
    "ZWE": "https://www.rbz.co.zw",
    "CPV": "https://www.bcv.cv",
    "PYF": "https://www.ieom.fr/polynesie-francaise/",
    "KIR": "https://www.kfsa.gov.ki/",
    "STP": "https://www.bcstp.st",
    "WSM": "https://www.cbs.gov.ws",
    "EUR": "https://www.ecb.europa.eu",
    "ECB": "https://www.ecb.europa.eu",
    "XAF": "https://www.beac.int",
    "BEAC": "https://www.beac.int/beac/le-gouvernement-de-la-banque/",
    "XOF": "https://www.bceao.int",
    "BCEAO": "https://www.bceao.int/en/content/governor",
    "XCD": "https://www.eccb-centralbank.org",
    "ECCB": "https://www.eccb-centralbank.org/about-us/governance",
    "ANT": "https://www.centralbank.cw",
}

SOURCE_COLLECTION = {
    "USA": "federalreserve.gov/aboutthefed/bios/board/boardmembership.htm",
    "CAN": "bankofcanada.ca/about/board-of-directors + Direct contact",
    "MEX": "banxico.org.mx/acerca-del-banco-de-mexico/junta-de-gobierno.html",
    "BRA": "bcb.gov.br/en/about/diretoriacolegiada + Direct contact",
    "ARG": "bcra.gob.ar/SobreElBCRA/Autoridades.asp + Direct contact",
    "CHL": "bcentral.cl/web/banco-central/el-banco/autoridades + Direct contact",
    "COL": "banrep.gov.co/es/junta-directiva + Direct contact",
    "PER": "bcrp.gob.pe/sobre-el-bcrp/directorio.html + Direct contact",
    "VEN": "bcv.org.ve/el-bcv/autoridades + Direct contact",
    "BOL": "bcb.gob.bo/webmaster/index.php + Direct contact",
    "URY": "bcu.gub.uy/Acerca-de/Paginas/Directorio.aspx + Direct contact",
    "PRY": "bcp.gov.py/Sobre-el-BCP/Directorio + Direct contact",
    "ECU": "bce.fin.ec/index.php/el-banco/autoridades + Direct contact",
    "CRI": "bccr.fi.cr/sobre_bccr/junta_directiva + Direct contact",
    "GTM": "banguat.gob.gt/Publicaciones/View.aspx + Direct contact",
    "HND": "bch.hn/bch/index.php + Direct contact",
    "SLV": "bcr.gob.sv/bcrsite + Direct contact",
    "NIC": "bcn.gob.ni/banco/directivos + Direct contact",
    "DOM": "bancentral.gov.do/a/d/2585-acerca + Direct contact",
    "JAM": "boj.org.jm/about + Direct contact",
    "TTO": "central-bank.org.tt/about-us + Direct contact",
    "HTI": "brh.net/index.php + Direct contact",
    "BHS": "centralbankbahamas.com/about + Direct contact",
    "BRB": "centralbank.org.bb/about-us + Direct contact",
    "GUY": "bankofguyana.org.gy/about + Direct contact",
    "SUR": "cbvs.sr/about + Direct contact",
    "BLZ": "centralbank.org.bz/about + Direct contact",
    "EUR": "ecb.europa.eu/ecb/decisions/eb/html/index.en.html",
    "GBR": "bankofengland.co.uk/about/people + Wikipedia MPC historical list",
    "DEU": "bundesbank.de/en/bundesbank/executive-board + Direct contact",
    "FRA": "banque-france.fr/en/banque-de-france/governance + Direct contact",
    "ITA": "bancaditalia.it/chi-siamo/governo/index.html + Direct contact",
    "ESP": "bde.es/es/sobre-el-bde/organigrama-y-gobierno + Direct contact",
    "PRT": "bportugal.pt/en/page/board-directors + Direct contact",
    "NLD": "dnb.nl/en/about-dnb/organisation/directorate + Direct contact",
    "BEL": "nbb.be/en/about-national-bank/governance + Direct contact",
    "CHE": "snb.ch/en/the-snb/organisation/governing-board + Direct contact",
    "SWE": "riksbank.se/en-gb/about-the-riksbank/organisation/executive-board + Direct contact",
    "NOR": "norges-bank.no/en/about/organisation/executive-board + Direct contact",
    "DNK": "nationalbanken.dk/en/aboutus/management + Direct contact",
    "FIN": "suomenpankki.fi/en/bank-of-finland/board-and-organisation/board + Direct contact",
    "ISL": "cb.is/about-the-bank/management + Direct contact",
    "IRL": "centralbank.ie/about/corporate-governance + Direct contact",
    "GRC": "bankofgreece.gr/en/about-us/governance + Direct contact",
    "AUT": "oenb.at/en/About-Us/Organisation + Direct contact",
    "POL": "nbp.pl/en/o_nbp/zarzad/index.html + Direct contact",
    "HUN": "mnb.hu/en/about-the-mnb/management + Direct contact",
    "CZE": "cnb.cz/en/about_cnb/bank_board + Direct contact",
    "SVK": "nbs.sk/en/about-nbs/governance + Direct contact",
    "SVN": "bsi.si/en/about-banka-slovenije/organisation + Direct contact",
    "HRV": "hnb.hr/en/about-us/governance + Direct contact",
    "BGR": "bnb.bg/AboutUs/AUBoardOfGovernors + Direct contact",
    "ROU": "bnr.ro/Board-of-Directors-2956.aspx + Direct contact",
    "EST": "eestipank.ee/en/estonian-economy/governing-bodies + Direct contact",
    "LVA": "bank.lv/en/about-the-bank/governing-bodies + Direct contact",
    "LTU": "lb.lt/en/about/management + Direct contact",
    "LUX": "bcl.lu/en/About-the-BCL/Gouvernance + Direct contact",
    "MLT": "centralbankmalta.org/about/governance + Direct contact",
    "CYP": "centralbank.cy/en-gb/the-bank/governance + Direct contact",
    "RUS": "cbr.ru/eng/about_br/bankboard + Direct contact",
    "UKR": "bank.gov.ua/en/about/management + Direct contact",
    "TUR": "tcmb.gov.tr/wps/wcm/connect/en/tcmb+en/main+menu/the+bank/governance + Direct contact",
    "BLR": "nbrb.by/engl/about/management + Direct contact",
    "SRB": "nbs.rs/en/o_narodnoj_banci/uprava + Direct contact",
    "BIH": "cbbh.ba/Content/Read/8 + Direct contact",
    "MKD": "nbrm.mk/en/governance + Direct contact",
    "MNE": "cbcg.me/en/about-us/governing-bodies + Direct contact",
    "ALB": "bankofalbania.org/en/Supervisory-Council-and-Board-of-Supervisors + Direct contact",
    "GEO": "nbg.gov.ge/en/monetary-policy/management + Direct contact",
    "ARM": "cba.am/en/SitePages/pboards.aspx + Direct contact",
    "AZE": "cbar.az/page-177/en + Direct contact",
    "KAZ": "nationalbank.kz/en/posts/rukovodstvo + Direct contact",
    "KGZ": "nbkr.kg/index.jsp?lang=ENG + Direct contact",
    "UZB": "cbu.uz/en/about/management + Direct contact",
    "TJK": "nbt.tj/en/about/management + Direct contact",
    "TKM": "cbt.gov.tm/en + Direct contact",
    "MDA": "bnm.md/en/content/management + Direct contact",
    "JPN": "boj.or.jp/en/about/organization/policyboard/index.htm + Direct contact",
    "CHN": "pbc.gov.cn/en/3688176/3688178/index.html + Direct contact",
    "IND": "rbi.org.in/Scripts/governors.aspx + Direct contact",
    "KOR": "bok.or.kr/eng/main/contents.do?menuNo=400028 + Direct contact",
    "IDN": "bi.go.id/en/tentang-bi/struktur/Contents/Default.aspx + Direct contact",
    "MYS": "bnm.gov.my/governor + Direct contact",
    "SGP": "mas.gov.sg/about-mas/board-and-management + Direct contact",
    "THA": "bot.or.th/en/about-us/management + Direct contact",
    "PHL": "bsp.gov.ph/SitePages/AboutTheBSP/Governors.aspx + Direct contact",
    "PAK": "sbp.org.pk/about/governor.asp + Direct contact",
    "BGD": "bb.org.bd/en/index.php/about/bbgovernor + Direct contact",
    "LKA": "cbsl.gov.lk/en/about-the-bank/board-of-directors + Direct contact",
    "NPL": "nrb.org.np/en/about-nrb/governors + Direct contact",
    "BTN": "rma.org.bt/about-rma/board-of-directors + Direct contact",
    "MDV": "mma.gov.mv/en/about/management + Direct contact",
    "VNM": "sbv.gov.vn/en/organization/governors.html + Direct contact",
    "KHM": "nbc.gov.kh/english/about_nbc/governor.php + Direct contact",
    "LAO": "bol.gov.la/index.php/en/about + Direct contact",
    "MMR": "cbm.gov.mm/en/node/1027 + Direct contact",
    "IRN": "cbi.ir/page/22736.aspx + Direct contact",
    "IRQ": "cbi.iq/index.php/en + Direct contact",
    "SAU": "sama.gov.sa/en-US/About/Pages/Governors.aspx + Direct contact",
    "ARE": "centralbank.ae/en/about-cbuae/board-of-directors + Direct contact",
    "KWT": "cbk.gov.kw/en/about-cbk/governor/current-governor + Direct contact",
    "QAT": "qcb.gov.qa/English/About/Pages/BoardOfDirectors.aspx + Direct contact",
    "BHR": "cbb.gov.bh/page-p-who-we-are + Direct contact",
    "OMN": "cbo.gov.om/sites/a/en/about/Pages/governor + Direct contact",
    "JOR": "cbj.gov.jo/En/Pages/About_CBJ_Governors.aspx + Direct contact",
    "LBN": "bdl.gov.lb/About-BDL/Governors + Direct contact",
    "ISR": "boi.org.il/en/about_boi/bod + Direct contact",
    "SYR": "cb.gov.sy/en + Direct contact",
    "HKG": "hkma.gov.hk/eng/about/hkmachiefexecutive.shtml + Direct contact",
    "TWN": "cbc.gov.tw/en/np-476-2.html + Direct contact",
    "MNG": "mongolbank.mn/en/governorsList + Direct contact",
    "ZAF": "resbank.co.za/en/home/about-us/governors + Direct contact",
    "NGA": "cbn.gov.ng/AboutCBN/Governors.asp + Direct contact",
    "EGY": "cbe.org.eg/en/about-cbe/governors + Direct contact",
    "MAR": "bkam.ma/en/About-Bank-Al-Maghrib/Governance + Direct contact",
    "DZA": "bank-of-algeria.dz/en/governors + Direct contact",
    "KEN": "centralbank.go.ke/about/former-governors + Direct contact",
    "GHA": "bog.gov.gh/about-us/governors-of-the-bank-of-ghana + Direct contact",
    "TZA": "bot.go.tz/about/governors + Direct contact",
    "ETH": "nbe.gov.et/about-us/former-governors + Direct contact",
    "UGA": "bou.or.ug/about/governance/governors + Direct contact",
    "RWA": "bnr.rw/en/former-governors + Direct contact",
    "ZMB": "boz.zm/about-boz/governors + Direct contact",
    "ZWE": "rbz.co.zw/index.php/about/governors + Direct contact",
    "SEN": "bceao.int/en/gouverneurs + Direct contact",
    "CIV": "bceao.int/en/gouverneurs + Direct contact",
    "CMR": "beac.int/en/governors + Direct contact",
    "COD": "bcc.cd/index.php/a-propos + Direct contact",
    "AGO": "bna.ao/en + Direct contact",
    "MOZ": "bancomoc.mz/en/about-us + Direct contact",
    "TUN": "bct.gov.tn/bct/siteprod/page.jsp?id=61 + Direct contact",
    "LBY": "cbl.gov.ly/en + Direct contact",
    "SDN": "cbos.gov.sd/en/node/3 + Direct contact",
    "MDG": "banque-centrale.mg/index_en + Direct contact",
    "MWI": "rbm.mw/index.php/about-the-rbm/governors + Direct contact",
    "NAM": "bon.com.na/about-us/governors + Direct contact",
    "BWA": "bankofbotswana.bw/about/governors + Direct contact",
    "LSO": "centralbank.org.ls/about/governors + Direct contact",
    "SWZ": "centralbank.org.sz/about/governors + Direct contact",
    "MUS": "bom.mu/en/about-bom/governors + Direct contact",
    "SYC": "cbs.sc/about + Direct contact",
    "GMB": "cbg.gm/about-us + Direct contact",
    "SLE": "bsl.gov.sl/about + Direct contact",
    "GIN": "bcrg-guinee.org/en + Direct contact",
    "BDI": "brb.bi/index.php/gouverneurs + Direct contact",
    "MLI": "bceao.int/en/gouverneurs + Direct contact",
    "NER": "bceao.int/en/gouverneurs + Direct contact",
    "BFA": "bceao.int/en/gouverneurs + Direct contact",
    "TGO": "bceao.int/en/gouverneurs + Direct contact",
    "BEN": "bceao.int/en/gouverneurs + Direct contact",
    "GNQ": "beac.int/en/governors + Direct contact",
    "GAB": "beac.int/en/governors + Direct contact",
    "COG": "beac.int/en/governors + Direct contact",
    "CAF": "beac.int/en/governors + Direct contact",
    "TCD": "beac.int/en/governors + Direct contact",
    "AUS": "rba.gov.au/about-rba/governors.html + Direct contact",
    "NZL": "rbnz.govt.nz/about-us/governors + Direct contact",
    "PNG": "bankpng.gov.pg/index.php/governors + Direct contact",
    "FJI": "rbf.gov.fj/about/governors + Direct contact",
    "SLB": "cbsi.com.sb/about-us + Direct contact",
    "VUT": "rbv.gov.vu/index.php/about-us + Direct contact",
    "TON": "nrbt.to/about + Direct contact",
    "WSM": "cbs.gov.ws/about + Direct contact",
    "ABW": "cba.aw/En/AboutUs + Direct contact",
    "BMU": "bma.bm/about-bma/board-of-directors + Direct contact",
    "CYM": "cima.ky/about/management + Direct contact",
    "MAC": "amcm.gov.mo/en/about/management + Direct contact",
}

DEFAULT_SOURCE_SCRAPED = "Direct contact with central bank / official website"
SOURCE_DATASET = "KOF ETH Zurich – cbg_turnover_v23"
DATASET_URL = "https://kof.ethz.ch/en/data/data-on-central-bank-governors.html"
